/**
 * Error Codes and Constants - Standardized error definitions
 */

const ERROR_CODES = {
  // Authentication errors (401-403)
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  
  // Input validation errors (400)
  BAD_REQUEST: 'BAD_REQUEST',
  MISSING_REQUIRED_FIELDS: 'MISSING_REQUIRED_FIELDS',
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_PAYMENT_METHOD: 'INVALID_PAYMENT_METHOD',
  
  // Not found errors (404)
  NOT_FOUND: 'NOT_FOUND',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  FEE_NOT_FOUND: 'FEE_NOT_FOUND',
  COUNTY_NOT_FOUND: 'COUNTY_NOT_FOUND',
  
  // Conflict errors (409)
  CONFLICT: 'CONFLICT',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  DUPLICATE_TRANSACTION: 'DUPLICATE_TRANSACTION',
  
  // Payment errors (402/422)
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_CREATION_FAILED: 'PAYMENT_CREATION_FAILED',
  PAYMENT_PROCESSING_FAILED: 'PAYMENT_PROCESSING_FAILED',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  RETRY_FAILED: 'RETRY_FAILED',
  MAX_RETRIES_EXCEEDED: 'MAX_RETRIES_EXCEEDED',
  
  // Blockchain errors (422)
  BLOCKCHAIN_ERROR: 'BLOCKCHAIN_ERROR',
  BLOCKCHAIN_RECORD_FAILED: 'BLOCKCHAIN_RECORD_FAILED',
  BLOCKCHAIN_QUERY_FAILED: 'BLOCKCHAIN_QUERY_FAILED',
  
  // Server errors (500+)
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  
  // Rate limiting (429)
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS'
};

const HTTP_STATUS_MAP = {
  // 4xx client errors
  [ERROR_CODES.UNAUTHORIZED]: 401,
  [ERROR_CODES.TOKEN_EXPIRED]: 401,
  [ERROR_CODES.TOKEN_INVALID]: 401,
  [ERROR_CODES.FORBIDDEN]: 403,
  
  [ERROR_CODES.BAD_REQUEST]: 400,
  [ERROR_CODES.MISSING_REQUIRED_FIELDS]: 400,
  [ERROR_CODES.INVALID_INPUT]: 400,
  [ERROR_CODES.INVALID_PAYMENT_METHOD]: 400,
  
  [ERROR_CODES.NOT_FOUND]: 404,
  [ERROR_CODES.TRANSACTION_NOT_FOUND]: 404,
  [ERROR_CODES.USER_NOT_FOUND]: 404,
  [ERROR_CODES.FEE_NOT_FOUND]: 404,
  [ERROR_CODES.COUNTY_NOT_FOUND]: 404,
  
  [ERROR_CODES.CONFLICT]: 409,
  [ERROR_CODES.RESOURCE_ALREADY_EXISTS]: 409,
  [ERROR_CODES.DUPLICATE_TRANSACTION]: 409,
  
  [ERROR_CODES.PAYMENT_FAILED]: 422,
  [ERROR_CODES.PAYMENT_CREATION_FAILED]: 422,
  [ERROR_CODES.PAYMENT_PROCESSING_FAILED]: 422,
  [ERROR_CODES.INSUFFICIENT_FUNDS]: 402,
  [ERROR_CODES.RETRY_FAILED]: 422,
  [ERROR_CODES.MAX_RETRIES_EXCEEDED]: 422,
  
  [ERROR_CODES.BLOCKCHAIN_ERROR]: 422,
  [ERROR_CODES.BLOCKCHAIN_RECORD_FAILED]: 422,
  [ERROR_CODES.BLOCKCHAIN_QUERY_FAILED]: 422,
  
  [ERROR_CODES.TOO_MANY_REQUESTS]: 429,
  
  // 5xx server errors (default)
  [ERROR_CODES.INTERNAL_ERROR]: 500,
  [ERROR_CODES.DATABASE_ERROR]: 500,
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 503
};

module.exports = {
  ERROR_CODES,
  HTTP_STATUS_MAP
};
